### ISSUE TITLE
CTOR does not check negative size 

### ISSUE THREAD

**Issue by Carvalanga** [cat4rsys/stack#4]
Hi again! Your macro DO_STACK_CTOR does not check negative size. Look at main:
#include "stack.h"
#include "log.h"
#include <cstdio>

int main()
{                                                                            
printf("ERROR LEXA LOH\n");                                                                                                                                                                                          
    Stack stk = {};

    stk.logFile = fopen("logfile.htm", "w");
    logInit(stk.logFile);

    DO_STACK_CTOR(&stk, -2);

    stackElem_t x = 0;

    for (int i = 0; i < 100; i++) {
        DO_STACK_PUSH(&stk, 11);
    }

    DO_STACK_POP(&stk, &x);

    DO_STACK_DUMP(&stk);

    DO_STACK_DTOR(&stk);

    return 0;
}

**Comment by Carvalanga** [comment]
BRO IT IS BUG IN STACK DTOR ABEME
void stackDtor(Stack * stk, int line, const char * file)
{
    free( (char *)stk->data - sizeof(canary_t) );
    stk->data = 0;
    stk->capacity = -1;
    DO_LOG_DUMP(stk->logFile, stk, line, file);
}
WHERE IS YOUR VERIFY AAAAAAAAAAAA?

**Comment by cat4rsys** [comment]
Okay, I will add it on next update
